[package]
name = "rand-ic"
description = "A Rust library for random number generation in IC."
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Froghub <f@froghub.io>"]
repository = "https://github.com/froghub-io/rand-ic.git"

[dependencies]
ic-cdk = "0.6.8"
